### ISSUE TITLE
Add organizing committee 

### ISSUE THREAD

**Issue by tngTUDOR** [Depart-de-Sentier/brightcon-2022-website#15]
After the logos of "... Jointly organized by ... ", Please add

-  a h3 Organizing committee 
- a list with: 
Chris Mutel 
Karin Treyer 
Tomás Navarrete Gutiérrez 

Link our names to our LinkedIn + Twitter + GitHub

**Comment by tngTUDOR** [comment]
![Screenshot_20220707-144431.png](https://user-images.githubusercontent.com/10451451/177777754-adf12e4b-64fa-4b55-b9af-2732b0a90412.png)

**Comment by tngTUDOR** [comment]
https://www.linkedin.com/in/karintreyer0777
https://github.com/KarinTreyer

https://www.linkedin.com/in/christopher-mutel-61b263b2
https://github.com/cmutel


https://www.linkedin.com/in/tom4m3
https://github.com/tngTUDOR
https://twitter.com/tomasN_list?t=l00iN9miHddObV3Ljy8m2A&s=09

**Comment by tngTUDOR** [comment]
There's a typo on "comitee" it should be committee @ackzell

**Comment by ok-lch** [comment]
Does something like that is good @tngTUDOR  ?
![Screenshot from 2022-07-07 17-09-38](https://user-images.githubusercontent.com/20227356/177808199-6471a861-4bd7-4efe-bbcb-60866e33433a.png)
(there is still a typo on committe on the screenshot)

**Comment by tngTUDOR** [comment]
Perfecto @LaurentChion .
Go ahead
